name: Lint
on: [push]
jobs:
  eslint_check:
    name: Prepare action
    runs-on: ubuntu-latest
    steps:
      # Checkout action must run prior to eslint check
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Lint
      uses: Krizzu/eslint-check-action@v1.1.0
      with:
        ghToken: ${{ secrets.TOKEN }}
        eslintFiles: "src"
        eslintConfig: ".eslintrc.json"
        eslintExt: "js"
